### ISSUE TITLE
Add Metrics Report

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#180]
# Issue description
*Describe your issue in detail here*

In the screenshot of the homework you can find multiple tasks what has to be done in the blogpost.

![Image](https://github.com/VisualGameData/VIGAD/assets/70775490/5a78afbb-8677-4f08-98f7-95c89f48824e)

## Update Documentation:
In the documentation we need to update multiple things i.e.

- [x] The Techstack which we are using: https://github.com/VisualGameData/VIGAD/wiki/Software-Requirements-Specification-(SRS)#23-technology-stack
- [x] Write something into the quality and metrics part of the documentation: https://github.com/VisualGameData/VIGAD/wiki/Software-Architecture-Document-(SAD)#11-qualitymetrics
- [x] Update the deployment view: https://github.com/VisualGameData/VIGAD/wiki/Software-Architecture-Document-(SAD)#7-deployment-view

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by BeierKevin** [comment]
The Blogposts maybe help:

https://reactprojectsite.wordpress.com/2018/06/13/metrics/
https://commonplayground.wordpress.com/week-8-enter-the-metrics/
https://partyplayer.wordpress.com/2020/05/30/week-15-metrics/
https://flashcardcommunity.wordpress.com/2019/05/28/week-8-metrics/

**Comment by Claiyc** [comment]
I guess this can be closed
