### ISSUE TITLE
Blog Post 12

### ISSUE THREAD

**Issue by BeierKevin** [VisualGameData/VIGAD#90]
# Issue description
*Describe your issue in detail here*

- [x] Showcase the new Create Session Mook-Up #85 
- [x] That we now have a Risk Management Setup #88 
- [ ] Our new Chart System #77 
- [x] And our updated wiki with the time spend per use case table #87 

https://wordpress.com/post/vigad.wordpress.com/394

# Definition Of Ready (DoR)
*This issue can be worked on if*
- [x] a developer is assigned
- [x] the issue is labeled
- [x] the issue is assigned to the current sprint
- [x] the issue is estimated
- [x] a meaningful title has been set
- [x] the issue is described in detail

**Comment by BeierKevin** [comment]
The Blog Post is almost done, we just need some information about the Chart System: https://wordpress.com/post/vigad.wordpress.com/394

**Comment by BeierKevin** [comment]
The published blogpost is right here: https://vigad.wordpress.com/2023/04/19/12-risk-management-time-and-much-more/
